23 refactor modules
bitshares/vuex-bitshares pull request #31
Opened 2018-10-24 18:13 UTC by ololokiras

Refactor modules in vuex lib to separate folders.

**Didn't remove getter with portfolio

2018-10-25 04:37 UTC, roma219 submitted a review, later dismissed

2018-10-25 04:39 UTC, roma219 commented
@ololokiras OK, but needs some tests file imports and lint fixes, build is failing:
![image](https://user-images.githubusercontent.com/4411295/47476426-08575500-d829-11e8-83f2-4d8260d7896b.png)

2018-10-26 12:28 UTC, youaresofunny requested changes
Lint & Fix tests please!

2018-10-27 11:43 UTC, roma219 requested changes
@ololokiras  Fix it asap

2018-10-28 14:57 UTC, merged