38 markets improve data
bitshares/vuex-bitshares pull request #47
Opened 2018-11-19 01:45 UTC by youaresofunny

Rewrote on `get_ticker`, 24h stats now in Market module

Merge first this one request in UI:
https://github.com/bitshares/bitshares-community-ui/pull/191

2018-11-20 18:43 UTC, roma219 requested changes
Needs fix to have 7d stats back

2018-11-20 18:43 UTC, roma219 commented on src/modules/market.js
> +      const stats = await market.fetchStats(quotes, fiatAsset);
Should return an Object with keys=quote symbols. It breaks fetching 7d market stats for now (see mutation)

2018-11-29 09:25 UTC, youaresofunny commented
@roma219 done

2018-12-01 09:17 UTC, roma219 approved these changes

2018-12-01 09:18 UTC, merged